# Copyright (c) Magistrala
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: magistrala
description: Magistrala IoT Platform
icon: https://avatars1.githubusercontent.com/u/13207490
type: application
version: 1.0.3
appVersion: "0.12.1"
home: https://www.magistrala.com
sources:
  - https://hub.docker.com/u/magistrala/
maintainers:
  - name: blokovi
    email: ivan.milosevic@magistrala.com
  - name: isavcic
    email: isavcic@gmail.com

dependencies:
  - name: nats
    version: "4.3.7"
    repository: "@stable"
  - name: postgresql
    version: "10.2.3"
    repository: "@bitnami"
    alias: postgresqlthings
    condition: postgresqlthings.enabled
  - name: postgresql
    version: "10.2.3"
    repository: "@bitnami"
    alias: postgresqlusers
    condition: postgresqlusers.enabled
  - name: postgresql
    version: "10.2.3"
    repository: "@bitnami"
    alias: postgresqlauth
    condition: postgresqlauth.enabled
  - name: postgresql
    version: "10.2.3"
    repository: "@bitnami"
    alias: postgresqlbootstrap
    condition: postgresqlbootstrap.enabled
  - name: postgresql
    version: "10.2.3"
    repository: "@bitnami"
    alias: postgresqlcerts
    condition: postgresqlcerts.enabled
  - name: postgresql
    version: "10.2.3"
    repository: "@bitnami"
    alias: postgresqlketo
    condition: postgresqlketo.enabled
  - name: redis
    version: "12.6.2"
    repository: "@bitnami"
    alias: redis-streams
  - name: redis
    version: "12.6.2"
    repository: "@bitnami"
    alias: redis-auth
  - name: redis
    version: "12.6.2"
    repository: "@bitnami"
    alias: redis-mqtt
  - name: redis
    version: "12.6.2"
    repository: "@bitnami"
    alias: redis-opcua
    condition: adapter_opcua.enabled
  - name: redis
    version: "12.6.2"
    repository: "@bitnami"
    alias: redis-lora
    condition: adapter_lora.enabled
  - name: influxdb
    version: "1.1.9"
    repository: "@bitnami"
    condition: influxdb.enabled
  - name: mongodb
    version: "10.4.1"
    repository: "@bitnami"
    alias: twins-db
    condition: twins.enabled
  - name: postgresql
    version: "10.2.3"
    repository: "@bitnami"
    alias: postgresqlnotifiersmtp
    condition: postgresqlnotifiersmtp.enabled
  - name: loki-stack
    version: "2.5.0"
    repository: "@grafana"
    condition: loki-stack.enabled
  - name: keto
    version: "0.21.7"
    repository: "@ory"
